# Generated by Django 5.0.6 on 2024-07-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='decription',
            new_name='description',
        ),
    ]
